// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv0Hdpzg6lzIKNuB752sLstP8rg5uHmGE',
    appId: '1:349759064384:web:a3c220c7bb0284951252a5',
    messagingSenderId: '349759064384',
    projectId: 'gideon-assistant-app',
    authDomain: 'gideon-assistant-app.firebaseapp.com',
    storageBucket: 'gideon-assistant-app.firebasestorage.app',
    measurementId: 'G-GZ6Q1MSHB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-WKQSNTKQlTDKpquWg9HPRn8Him2n_e0',
    appId: '1:349759064384:android:51dd3cb8e312e5e01252a5',
    messagingSenderId: '349759064384',
    projectId: 'gideon-assistant-app',
    storageBucket: 'gideon-assistant-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCLpcfinGdphMrGzlU96T_lScKDhi0ngU',
    appId: '1:349759064384:ios:394b4c8b087c2b781252a5',
    messagingSenderId: '349759064384',
    projectId: 'gideon-assistant-app',
    storageBucket: 'gideon-assistant-app.firebasestorage.app',
    androidClientId: '349759064384-fiahep03mlnb9gifqvimr705c1504l7b.apps.googleusercontent.com',
    iosClientId: '349759064384-ntsprhrl23iltcibbkgcl7v51dtimdko.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAiApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCLpcfinGdphMrGzlU96T_lScKDhi0ngU',
    appId: '1:349759064384:ios:394b4c8b087c2b781252a5',
    messagingSenderId: '349759064384',
    projectId: 'gideon-assistant-app',
    storageBucket: 'gideon-assistant-app.firebasestorage.app',
    androidClientId: '349759064384-fiahep03mlnb9gifqvimr705c1504l7b.apps.googleusercontent.com',
    iosClientId: '349759064384-ntsprhrl23iltcibbkgcl7v51dtimdko.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv0Hdpzg6lzIKNuB752sLstP8rg5uHmGE',
    appId: '1:349759064384:web:876ae605184a19c01252a5',
    messagingSenderId: '349759064384',
    projectId: 'gideon-assistant-app',
    authDomain: 'gideon-assistant-app.firebaseapp.com',
    storageBucket: 'gideon-assistant-app.firebasestorage.app',
    measurementId: 'G-GWPJMLMB0D',
  );
}
